In [2]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3,"ani"],dtype=object)
arr1

array([1, 2, 3, 'ani'], dtype=object)

In [5]:
normal_arr = ["ani",1,2]
normal_arr

['ani', 1, 2]

In [3]:
two_d_arr = np.array([[1,2,3]
                      ,[4,5,6]])
two_d_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
three_arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]]
)

three_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr_zeros = np.zeros((111,111))
arr_zeros

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(111, 111))

In [17]:
arr_ones = np.ones((2,2),dtype=str)
arr_ones

array([['1', '1'],
       ['1', '1']], dtype='<U1')